version: '2'
services:
  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: nwrjaouokbcuswlkknkmt
    depends_on:
      - db
    restart: always
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nwrjaouokbcuswlkknkmt
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
